development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: octo-crowd-development
  pool: 5
  username: octo-crowd

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: octo-crowd-test
  pool: 5
  username: octo-crowd

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: octo-crowd-production
  pool: 5
  username: octo-crowd
  password: octo-crowd
