facebook:
  id: "1393731560863436"
  secret: "84ba18cedbbf3f872df8d7e745ec202d"

vkontakte:
  id: "3936430"
  secret: "dBFZLW0nU7thpkhHBOS4"

twitter:
  id: "yPGkPLAr6K11OKXXW4utQ"
  secret: "OVjS5FrSxBjbHDGZFfBeI3wcArbh9Rdml6tIcCZkA"