facebook:
  id: "662771950424295"
  secret: "55b79d00921eab9d9f13fc393603fdac"

vkontakte:
  id: "3936430"
  secret: "dBFZLW0nU7thpkhHBOS4"

twitter:
  id: "86073382-Gm4pW33XjxeqKeXijMkVSrSglcvKnZkAfcSQLHocU"
  secret: "nHPSiTH6BR5LzUcgmm7NRqPmP8pHl6rXnF7e8Yho6DGk4"